### ISSUE TITLE
bug in cmake/qpc_sdk_import.cmake and toolchain improvements

### ISSUE THREAD

**Issue by stefanschober** [QuantumLeaps/3rd_party#2]
Hi Miro,

I discovered an ugly bug in [qpc_sdk_import.cmake](https://github.com/QuantumLeaps/3rd_party/tree/main/cmake/qpc_sdk_import.cmake), which disables the automatic download of `qpc` from your GitHub repository. The attached [diff file](https://github.com/QuantumLeaps/3rd_party/files/14342860/cmake_diff.zip) fixes this bug and it also adds `-DQ_SPY` to all [toolchain files](https://github.com/QuantumLeaps/3rd_party/tree/main/cmake/toolchain)

After this I would also consider my pull requests as closed.

**Comment by quantum-leaps** [comment]
The diff has been applied and pushed into the 3rd_party repo. Please check, and close the issue if OK.
Thanks,
--MMS
