### ISSUE TITLE
CMake updates to enhance compatibility with recent versions of CMake (3.29++)

### ISSUE THREAD

**Issue by stefanschober** [QuantumLeaps/3rd_party#3]
- updates in `cmake/qpc_sdk_import.cmake` and `cmake/qpcpp_sdk_import.cmake`

[3rd_party.cmake.diff.zip](https://github.com/user-attachments/files/17568600/3rd_party.cmake.diff.zip)

**Comment by quantum-leaps** [comment]
Merged and pushed into the qpc and qpcpp repos.
Thank you,
--MMS
